### ISSUE TITLE
EMR training failing due to pomegranate versioning.

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-stack-analysis#102]
```
Installing collected packages: cython, uuid, botocore, s3transfer, boto3, pandas, scikit-learn, sklearn, psutil
  Running setup.py install for cython
  Running setup.py install for uuid
  Found existing installation: botocore 1.4.86
    Uninstalling botocore-1.4.86:
      Successfully uninstalled botocore-1.4.86
  Running setup.py install for pandas
  Running setup.py install for scikit-learn
  Running setup.py install for sklearn
  Running setup.py install for psutil
Successfully installed boto3-1.4.7 botocore-1.7.36 cython-0.27.2 pandas-0.21.0 psutil-5.4.0 s3transfer-0.1.11 scikit-learn-0.19.1 sklearn-0.0 uuid-1.30
Requirement already satisfied (use --upgrade to upgrade): nltk in /usr/local/lib/python2.7/site-packages
Collecting pomegranate
  Downloading pomegranate-0.8.1.tar.gz (2.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/mnt/tmp/pip-build-DKRWWw/pomegranate/setup.py", line 34, in <module>
        extensions = cythonize( extensions )
      File "/usr/local/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 920, in cythonize
        aliases=aliases)
      File "/usr/local/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 800, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/local/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 125, in nonempty
        raise ValueError(error_msg)
    ValueError: 'pomegranate/*.pyx' doesn't match any files
    
    ----------------------------------------

```

**Comment by sara-02** [comment]
Fixed.
